- package: mnist
  version: 1.5.0
  description: softmax classifier for mnist digits
  url: https://github.com/PipelineAI/models
  author: PipelineAI
  author-email: contact@pipeline.ai
  license: Apache 2.0
  tags: [mnist, images, model]

# -------------------------------------------------------------------
# base config
# -------------------------------------------------------------------

- config: base
  operations:
    train:
      description: 'Train the {{model_desc}}'
      cmd: '{{train_cmd}} --data-dir mnist-idx-data --run-dir .'
      flags:
        batch-size:
          description: Number of images to include in a training batch
          default: 100
        epochs:
          description: Number of epochs to train
          default: 5
    evaluate:
      description: 'Evaluate a trained {{model_desc}}'
      cmd: '{{train_cmd}} --test --data-dir mnist-idx-data --run-dir .'
      requires:
        - trained-model
  resources:
    trained-model:
      private: yes
      sources:
        - operation: train
          select:
            - model.ckpt.*
            - checkpoint

- model: mnist-v1 
  description: softmax version of MNIST
  extends: base
  params:
    model_desc: softmax regression
    train_cmd: pipeline_train 
    model_name: mnist
    model_tag: v1
    model_type: tensorflow
    model_runtime: tfserving
    model_chip: cpu
