- package: mnist
  version: v3
  author-email:
  tags: [mnist, v1, keras, model]

# -------------------------------------------------------------------
# base (shared config)
# -------------------------------------------------------------------

- config: base
  operations:
    train:
      description: 'Train'
      cmd: 'pipeline_train'
      flags:
        batch_size:
          description: Number of images to include in a training batch
          default: 1
        data_dir:
          description: Training dataset
          default: ./input/training
        model_dir:
          description: Output directory
          default: ./checkpoint
        train_epochs:
          description: Training epochs
          default: 1
        epochs_between_evals:
          description: Epochs between evaluation runs 
          default: 1
    evaluate:
      description: 'Evaluate'
      cmd: 'pipeline_train --test'
      requires:
        - trained-model
  resources:
    trained-model:
      private: yes
      sources:
        - operation: train
          select:
            - model.ckpt.*
            - checkpoint

- model: mnist
  extends: base
  params:
    model_desc: mnist
    train_cmd: pipeline_train
    model_name: mnist
    model_tag: v1
    model_type: keras 
    model_runtime: tfserving
    model_chip: cpu
