- package: mnist
  version: 1.5.0
  description: softmax classifier for mnist digits
  url: https://github.com/PipelineAI/models
  author: PipelineAI
  author-email: contact@pipeline.ai
  license: Apache 2.0
  tags: [mnist, images, model]
#  resources:
#    dataset:
#      description: "Yann Lecun's MNIST dataset in compressed IDX format"
#      path: mnist-idx-data
#      sources:
#        - url: http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
#          sha256: 440fcabf73cc546fa21475e81ea370265605f56be210a4024d2ca8f203523609
#        - url: http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
#          sha256: 3552534a0a558bbed6aed32b30c495cca23d567ec52cac8be1a0730e8010255c
#        - url: http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
#          sha256: 8d422c7b0a1c1c79245a5bcf07fe86e33eeafee792b84584aec276f5a2dbc4e6
#        - url: http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
#          sha256: f7ae60f92e00ec6debd23a6088c31dbd2371eca3ffa0defaefb259924204aec6

# -------------------------------------------------------------------
# mnist-base (shared config)
# -------------------------------------------------------------------

- config: mnist-base
  operations:
    train:
      description: 'Train the {{model_desc}}'
      cmd: '{{train_cmd}} --data-dir mnist-idx-data --run-dir .'
#      requires: mnist/dataset
      flags:
        batch-size:
          description: Number of images to include in a training batch
          default: 100
        epochs:
          description: Number of epochs to train
          default: 5
    evaluate:
      description: 'Evaluate a trained {{model_desc}}'
      cmd: '{{train_cmd}} --test --data-dir mnist-idx-data --run-dir .'
      requires:
        - trained-model
#        - mnist/dataset
  resources:
    trained-model:
      private: yes
      sources:
        - operation: train
          select:
            - model.ckpt.*
            - checkpoint

- model: mnist-v3
  description: softmax version of MNIST
  extends: mnist-base
  params:
    model_desc: softmax regression
    train_cmd: pipeline_train 
    model_name: mnist
    model_tag: v3
    model_type: tensorflow
    model_runtime: tfserving
    model_chip: cpu

# Generated by us
#- model: softmaxt_16bit_quantization_tensorrt_gpu 
#  description: softmax version of MNIST built 
#  extends: mnist-base
#  params:
#    model_desc: softmax regression
#    train_cmd: pipeline_train
#    model_name: mnistsoftmax
#    model_tag: tensorflowtfservingcpu
#    model_type: tensorflow
#    model_runtime: tfserving
#    model_chip: cpu


#- model: softmax_16bit_quantization_tensor_gpu
#  description: softmax version of MNIST built
#  extends: mnist-base
#  params:
#  - model_name: mnistsoftmax
#    model_tag: tensorflowtfservinggpu
#    model_type: tensorflow
#    model_runtime: tfserving
#    model_chip: gpu


#- model: softmax_16bit_quantization_tensor_gpu
#  description: softmax version of MNIST built
#  extends: mnist-base
#  params:
#  - model_name: mnistsoftmax
#    model_tag: tensorflowtensorrtgpu
#    model_type: tensorflow 
#    model_runtime: tensorrt
#    model_chip: gpu


# -------------------------------------------------------------------
# mnist-samples
# -------------------------------------------------------------------

#- model: mnist-samples
#  description: Sample MNIST images
#  operations:
#    prepare:
#      description: Generate a set of sample MNIST images
#      cmd: samples --data-dir mnist-idx-data --sample-dir .
#      flags:
#        count:
#          description: Number of images to generate
#          default: 100
#          arg-name: sample-count
#      requires: mnist/dataset
