- package: mnist
  version: v3
  author-email:
  tags: [mnist, v1, model]

# -------------------------------------------------------------------
# base (shared config)
# -------------------------------------------------------------------

- config: base
  operations:
    train:
      description: 'Train'
      cmd: 'pipeline_train'
      flags:
        batch-size:
          description: Number of images to include in a training batch
          default: 1
        data-dir:
          description: Training dataset
          default: ./input/training
        model-dir:
          description: Output directory
          default: ./checkpoint
        train-steps:
          description: Training steps
          default: 1
    evaluate:
      description: 'Evaluate'
      cmd: 'pipeline_train --test'
      requires:
        - trained-model
  resources:
    trained-model:
      private: yes
      sources:
        - operation: train
          select:
            - model.ckpt.*
            - checkpoint

- model: mnist
  extends: base
  params:
    model_desc: mnist
    train_cmd: pipeline_train
    model_name: mnist
    model_tag: v3
    model_type: tensorflow
    model_runtime: tfserving
    model_chip: cpu
