- package: census 
  version: 1.5.0
  description: census
  url: https://github.com/PipelineAI/models
  author: PipelineAI
  author-email: contact@pipeline.ai
  license: Apache 2.0
  tags: [census, model]

# -------------------------------------------------------------------
# base config
# -------------------------------------------------------------------

- config: base
  operations:
    train:
      description: 'Train'
      cmd: 'pipeline_train'
      flags:
        batch-size:
          description: Number of images to include in a training batch
          default: 100
        epochs:
          description: Number of epochs to train
          default: 5
    evaluate:
      description: 'Evaluate'
      cmd: 'pipeline_train'
      requires:
        - trained-model
  resources:
    trained-model:
      private: yes
      sources:
        - operation: train
          select:
            - model.ckpt.*
            - checkpoint

- model: census
  description: softmax version of MNIST
  extends: base
  params:
    model_desc: cool census model 
    train_cmd: pipeline_train
    model_name: census 
    model_tag: v1
    model_type: xgboost 
    model_runtime: jvm
    model_chip: cpu
