- package: mnist
  version: v4
  author-email:
  tags: [mnist, v4, tensorflow, model]

# -------------------------------------------------------------------
# base (shared config)
# -------------------------------------------------------------------

- config: base
  operations:
    train:
      description: 'Train'
      cmd: 'pipeline_train'
      flags:
        export_dir:
          description: Export dir
          default: ./pipeline_tfserving  
    evaluate:
      description: 'Evaluate'
      cmd: 'pipeline_train --test'
      requires:
        - trained-model
  resources:
    trained-model:
      private: yes
      sources:
        - operation: train
          select:
            - model.ckpt.*
            - checkpoint

- model: mnist
  extends: base
  params:
    model_desc: mnist
    train_cmd: pipeline_train
    model_name: mnist
    model_tag: v4
    model_type: tensorflow
    model_runtime: tfserving
    model_chip: cpu
