- package: mnist
  version: 1.5.0
  description: digits
  url: https://github.com/PipelineAI/models
  author: PipelineAI
  author-email: contact@pipeline.ai
  license: Apache 2.0
  tags: [mnist, images, model]

# -------------------------------------------------------------------
# mnist-base (shared config)
# -------------------------------------------------------------------

- config: mnist-base
  operations:
    train:
      description: 'Train'
      cmd: 'pipeline_train --tpu tpu-us-centra1-c-00 --tpu-zone us-central1-c --gcp-project flux-capacitor1 --data-dir ../input/training --model_dir ./pipeline_tfserving/0 .'
      flags:
        batch-size:
          description: Number of images to include in a training batch
          default: 100
        epochs:
          description: Number of epochs to train
          default: 5

    evaluate:
      description: 'Evaluate'
      cmd: 'pipeline_train --test --data-dir ../input/training --model-dir ../output/validation .'
      requires:
        - trained-model
  resources:
    trained-model:
      private: yes
      sources:
        - operation: train
          select:
            - model.ckpt.*
            - checkpoint

- model: mnist
  description: official mnist
  extends: mnist-base
  params:
    model_desc: cnn
    train_cmd: pipeline_train
    model_name: mnist
    model_tag: v5
    model_type: tensorflow
    model_runtime: tfserving
    model_chip: cpu
