dependencies:
  - openssl=1.0.2l=0
  - pandas=0.22.0
  - numpy=1.14.0
  - python>=3.6
  - pytz=2017.2
  - scikit-learn=0.19.1
  - scipy=1.0.0
  - setuptools=27.2.0
  - six=1.10.0
  - wheel=0.29.0
  - h5py=2.7.0
  - pip:  
    - keras==2.1.6
    - tensorflow==1.8.0
    - tensorboard==1.8.0
    - pipeline-runtime==1.0.8
