dependencies:
  - pip=9.0.1
  - python=3.6
  - pip:
    - grpcio>=1.0
    - tensorflow==1.8.0
    - tensorboard==1.8.0
    - pipeline-runtime==1.0.8
#    - psutil>=5.4.3
#    - py-cpuinfo>=3.3.0
#    - google-cloud-bigquery>=0.31.0
