- package: e30e79aamnist
  version: ktag
  author-email:
  tags: [e30e79aamnist, ktag, keras, model]

# -------------------------------------------------------------------
# base (shared config)
# -------------------------------------------------------------------

- config: base
  operations:
    train:
      description: 'Train'
      cmd: 'pipeline_train'
      flags:
        model_dir:
          description: Model dir
          default: .
    evaluate:
      description: 'Evaluate'
      cmd: 'pipeline_train'
      requires:
        - trained-model
  resources:
    trained-model:
      private: yes
      sources:
        - operation: train
          select:
            - model.ckpt.*
            - checkpoint

- model: e30e79aamnist
  extends: base
  params:
    train_cmd: pipeline_train
    model_desc: e30e79aamnist
    model_name: e30e79aamnist
    model_tag: ktag
    model_type: keras
#    model_runtime:
    model_chip: cpu