- package: airbnb 
  version: 1.5.0
  description: airbnb pytorch
  url: https://github.com/PipelineAI/models
  author: PipelineAI
  author-email: contact@pipeline.ai
  license: Apache 2.0
  tags: [airbnb, model]

# -------------------------------------------------------------------
# base config
# -------------------------------------------------------------------

- config: base
  operations:
    train:
      description: 'Train'
      cmd: 'pipeline_train'
    evaluate:
      description: 'Evaluate'
      cmd: 'pipeline_train'
      requires:
        - trained-model
  resources:
    trained-model:
      private: yes
      sources:
        - operation: train
          select:
            - model.ckpt.*
            - checkpoint

- model: airbnb 
  description: airbnb
  extends: base
  params:
    model_desc: airbnb
    train_cmd: pipeline_train
    model_name: airbnb
    model_tag: v1
    model_type: python 
    model_runtime: python 
    model_chip: cpu
