channels:
  - conda-forge 
dependencies:
  - python=3.6.1=2
  - pip=9.0.1
  - mkl=2017.0.1=0
  - mkl-service=1.1.2
  - numpy=1.14.0
  - pandas=0.20.2
  - scikit-learn=0.18.2
  - ujson=1.35
  - pip:
    - pipeline-runtime>=1.0.3
