- package: inception
  version: v1
  author-email: 
  tags: [inception, v1, model]

# -------------------------------------------------------------------
# base (shared config)
# -------------------------------------------------------------------

- config: base
  operations:
    train:
      description: 'Train the {{model_desc}}'
      cmd: '{{train_cmd}}'
      flags:
        batch-size:
          description: Number of images to include in a training batch
          default: 1 
        data-dir:
          description: Training dataset
          default: ../input/training
        model-dir:
          description: Output directory
          default: ./checkpoint
        train-steps: 
          description: Training steps
          default: 1
    evaluate:
      description: 'Evaluate a trained {{model_desc}}'
      cmd: '{{train_cmd}}'
      requires:
        - trained-model
  resources:
    trained-model:
      private: yes
      sources:
        - operation: train
          select:
            - model.ckpt.*
            - checkpoint
- model: inception
  extends: base
  params:
    model_desc: inception 
    train_cmd: pipeline_train
    model_name: inception 
    model_tag: v1
    model_type: tensorflow
    model_runtime: tfserving
    model_chip: cpu
