- package: mnist
  version: 1.5.0
  description: v2 cnn classifier for mnist digits
  url: https://github.com/PipelineAI/models
  author: PipelineAI
  author-email: contact@pipeline.ai
  license: Apache 2.0
  tags: [mnist, images, model]
# -------------------------------------------------------------------
# mnist-base (shared config)
# -------------------------------------------------------------------

- config: mnist-base
  operations:
    train:
      description: 'Train the {{model_desc}}'
      cmd: '{{train_cmd}} --data-dir mnist-idx-data --run-dir .'
      flags:
        batch-size:
          description: Number of images to include in a training batch
          default: 100
        epochs:
          description: Number of epochs to train
          default: 5
    evaluate:
      description: 'Evaluate a trained {{model_desc}}'
      cmd: '{{train_cmd}} --test --data-dir mnist-idx-data --run-dir .'
      requires:
        - trained-model
  resources:
    trained-model:
      private: yes
      sources:
        - operation: train
          select:
            - model.ckpt.*
            - checkpoint

- model: mnist
  description: cnn version of MNIST
  extends: mnist-base
  params:
    model_desc: cnn version of MNIST
    train_cmd: pipeline_train
    model_name: mnist
    model_tag: v2
    model_type: tensorflow
    model_runtime: tfserving
    model_chip: cpu

